# Generated by Django 2.2.1 on 2019-05-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vakte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ushqimet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=50)),
                ('sasi', models.IntegerField()),
                ('kalori', models.FloatField()),
                ('proteina', models.FloatField()),
                ('sheqerna', models.FloatField()),
                ('yndyrna', models.FloatField()),
                ('fibra', models.FloatField()),
                ('sasi_total', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='media')),
                ('vaktet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HealthApp.Vakte')),
            ],
        ),
    ]
