# Generated by Django 2.2.1 on 2019-05-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pyetesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesha', models.IntegerField()),
                ('gjatesia', models.IntegerField()),
            ],
        ),
    ]
