# Generated by Django 2.2.1 on 2019-05-27 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HealthApp', '0003_auto_20190526_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyetesor',
            name='user',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
