# Generated by Django 2.2.1 on 2019-05-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0004_pyetesor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ushqimet',
            name='vaktet',
        ),
        migrations.AddField(
            model_name='ushqimet',
            name='vakti',
            field=models.CharField(default='', max_length=20),
        ),
    ]
