# Generated by Django 2.2.1 on 2019-05-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0005_auto_20190529_1445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ushqimet',
            new_name='Mengjesi',
        ),
    ]
