# Generated by Django 2.2.1 on 2019-05-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0006_auto_20190529_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mengjesi',
            name='vakti',
            field=models.CharField(choices=[('Mengjesi', 'Mengjesi'), ('Dreka', 'Dreka'), ('Darka', 'Darka'), ('Snacks', 'Snacks')], max_length=20),
        ),
    ]
