# Generated by Django 2.2.1 on 2019-05-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0008_remove_mengjesi_vakti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Darka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=50)),
                ('sasi', models.IntegerField()),
                ('kalori', models.FloatField()),
                ('proteina', models.FloatField()),
                ('sheqerna', models.FloatField()),
                ('yndyrna', models.FloatField()),
                ('fibra', models.FloatField()),
                ('sasi_total', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Dreka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=50)),
                ('sasi', models.IntegerField()),
                ('kalori', models.FloatField()),
                ('proteina', models.FloatField()),
                ('sheqerna', models.FloatField()),
                ('yndyrna', models.FloatField()),
                ('fibra', models.FloatField()),
                ('sasi_total', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=50)),
                ('sasi', models.IntegerField()),
                ('kalori', models.FloatField()),
                ('proteina', models.FloatField()),
                ('sheqerna', models.FloatField()),
                ('yndyrna', models.FloatField()),
                ('fibra', models.FloatField()),
                ('sasi_total', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='media')),
            ],
        ),
    ]
