# Generated by Django 2.2.1 on 2019-06-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0010_aktiviteti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport_Natyre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=50)),
                ('koeficienti', models.FloatField()),
                ('foto', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Sport_Palester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=50)),
                ('koeficienti', models.FloatField()),
                ('foto', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Sport_Ujore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=50)),
                ('koeficienti', models.FloatField()),
                ('foto', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.RenameModel(
            old_name='Aktiviteti',
            new_name='Sport_Grupe',
        ),
    ]
