# Generated by Django 2.2.1 on 2019-06-09 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HealthApp', '0011_auto_20190606_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out', models.BooleanField(default=False)),
                ('dreke', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HealthApp.Dreka')),
                ('mengjesi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HealthApp.Mengjesi')),
                ('snacks', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HealthApp.Snacks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
